image: pobj

stages:
- test

TME-4:
  script: >
    /home/pobj/run.sh -id TME-4 -name TME-4
    pobj.multiset.test.HashMultiSetTest
    pobj.multiset.test.IteratorTest
    pobj.multiset.test.CollectionTest
    pobj.multiset.test.HashMultiSetTest2
  artifacts:
    reports:
      junit: report.xml
